# Generated by Django 3.2.9 on 2021-11-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
                ('mobile_num', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('age_catg', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('album_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('shared_list', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('rel_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'friends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('size_img', models.FloatField()),
                ('dim_w', models.IntegerField()),
                ('dim_h', models.IntegerField()),
                ('file_type', models.CharField(max_length=30)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('shared_list', models.CharField(blank=True, max_length=500, null=True)),
                ('age_catg_allowed', models.IntegerField()),
                ('copyright_status', models.BooleanField()),
            ],
            options={
                'db_table': 'gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('d_o_b', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.accounts')),
                ('user_name', models.CharField(max_length=30)),
                ('user_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_location', models.CharField(blank=True, max_length=30, null=True)),
                ('age_catg', models.IntegerField()),
                ('interests', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
