# Generated by Django 3.2.9 on 2021-12-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20211201_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
