# Generated by Django 3.2.9 on 2021-11-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
