# Generated by Django 3.2.9 on 2021-12-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_delete_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
