# Generated by Django 3.2.9 on 2021-12-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20211201_0830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Albums',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
